# This affects access control for clients with no username.
topic read $SYS/#
topic #

# This affects all clients.
pattern write $SYS/broker/connection/%c/state
pattern read kp/%c/#
pattern write kp/MAC/%c/#
pattern write kp/MACap/%c/#

# kp/FFFFFFFFFFFF/# BCAST Address
pattern read kp/FFFFFFFFFFFF/#
