-- Copyright 2008 Steven Barth <steven@midlink.org>
-- Licensed to the public under the Apache License 2.0.

local fs = require("nixio.fs")

local _translate = translate
local zh = {
	["Accept options pushed from server"] = "接受服务端下发的选项",
	["Add route after establishing connection"] = "连接建立后添加路由",
	["Additional authentication over TLS"] = "TLS 附加认证",
	["Allow client-to-client traffic"] = "允许客户端之间互访",
	["Allow multiple clients with same certificate"] = "允许多个客户端使用同一证书",
	["Allow only one session"] = "仅允许单个会话",
	["Allow remote to change its IP or port"] = "允许对端变更 IP 或端口",
	["Allowed maximum of connected clients"] = "允许的最大连接客户端数",
	["Allowed maximum of internal"] = "允许的最大内部条目数",
	["Allowed maximum of new connections"] = "允许的最大新连接数",
	["Append log to file"] = "追加日志到文件",
	["Authenticate using username/password"] = "使用用户名/密码认证",
	["Automatically redirect default route"] = "自动重定向默认路由",
	["Call down cmd/script before TUN/TAP close"] = "在关闭 TUN/TAP 前执行 down 脚本",
	["Certificate authority"] = "CA 证书",
	["Change process priority"] = "调整进程优先级",
	["Change to directory before initialization"] = "初始化前切换到目录",
	["Check peer certificate against a CRL"] = "使用 CRL 校验对端证书",
	["Chroot to directory after initialization"] = "初始化后 chroot 到目录",
	["Client is disabled"] = "客户端已禁用",
	["Configure client mode"] = "配置客户端模式",
	["Configure server bridge"] = "配置服务端桥接",
	["Configure server mode"] = "配置服务端模式",
	["Connect through Socks5 proxy"] = "通过 Socks5 代理连接",
	["Connect to remote host through an HTTP proxy"] = "通过 HTTP 代理连接远端",
	["Connection retry interval"] = "连接重试间隔",
	["Cryptography"] = "加密",
	["Daemonize after initialization"] = "初始化后转入守护进程",
	["Delay n seconds after connection"] = "连接后延迟 n 秒",
	["Delay tun/tap open and up script execution"] = "延迟打开 tun/tap 并执行 up 脚本",
	["Diffie-Hellman parameters"] = "Diffie-Hellman 参数",
	["Directory for custom client config files"] = "自定义客户端配置目录",
	["Disable options consistency check"] = "禁用选项一致性检查",
	["Disable Paging"] = "禁止内存换页",
	["Do not bind to local address and port"] = "不绑定本地地址和端口",
	["Don't actually execute ifconfig"] = "不实际执行 ifconfig",
	["Don't add routes automatically"] = "不自动添加路由",
	["Don't cache --askpass or --auth-user-pass passwords"] = "不缓存 --askpass 或 --auth-user-pass 密码",
	["Don't drop incoming tun packets with same destination as host"] = "不丢弃目标与主机相同的入站 tun 报文",
	["Don't inherit global push options"] = "不继承全局 push 选项",
	["Don't log timestamps"] = "日志不写时间戳",
	["Don't pull routes automatically"] = "不自动拉取路由",
	["Don't re-read key on restart"] = "重启时不重新读取密钥",
	["Don't use adaptive lzo compression"] = "不使用自适应 LZO 压缩",
	["Don't warn on ifconfig inconsistencies"] = "不对 ifconfig 不一致发出警告",
	["Echo parameters to log"] = "将参数回显到日志",
	["Empirically measure MTU"] = "经验性测量 MTU",
	["Enable a compression algorithm"] = "启用压缩算法",
	["Enable internal datagram fragmentation"] = "启用内部数据报分片",
	["Enable management interface on <em>IP</em> <em>port</em>"] = "在 <em>IP</em> <em>端口</em> 启用管理接口",
	["Enable OpenSSL hardware crypto engines"] = "启用 OpenSSL 硬件加密引擎",
	["Enable Path MTU discovery"] = "启用路径 MTU 发现",
	["Enable Static Key encryption mode (non-TLS)"] = "启用静态密钥加密模式（非 TLS）",
	["Enable TLS and assume client role"] = "启用 TLS 并作为客户端",
	["Enable TLS and assume server role"] = "启用 TLS 并作为服务端",
	["Encrypt and authenticate all control channel packets with the key"] = "使用该密钥加密并认证所有控制通道数据包",
	["Encryption cipher for packets"] = "数据包加密算法",
	["Execute shell cmd after routes are added"] = "路由添加后执行 shell 命令",
	["Execute shell command on remote IP change"] = "远端 IP 变化时执行 shell 命令",
	["Executed in server mode on new client connections, when the client is still untrusted"] = "服务端模式下新客户端连接且尚未可信时执行",
	["Executed in server mode whenever an IPv4 address/route or MAC address is added to OpenVPN's internal routing table"] = "服务端模式下每次向 OpenVPN 内部路由表添加 IPv4 地址、路由或 MAC 时执行",
	["Exit on TLS negotiation failure"] = "TLS 协商失败时退出",
	["Get PEM password from controlling tty before we daemonize"] = "守护化前从控制终端读取 PEM 密码",
	["Handling of authentication failures"] = "认证失败处理方式",
	["Helper directive to simplify the expression of --ping and --ping-restart in server mode configurations"] = "用于简化服务端模式下 --ping 与 --ping-restart 的辅助指令",
	["HMAC authentication for packets"] = "数据包 HMAC 认证",
	["If hostname resolve fails, retry"] = "主机名解析失败时重试",
	["Keep local IP address on restart"] = "重启时保留本地 IP 地址",
	["Keep remote IP address on restart"] = "重启时保留远端 IP 地址",
	["Keep tun/tap device open on restart"] = "重启时保持 tun/tap 设备打开",
	["Key transition window"] = "密钥轮换窗口",
	["Limit repeated log messages"] = "限制重复日志消息",
	["Local certificate"] = "本地证书",
	["Local host name or IP address"] = "本地主机名或 IP 地址",
	["Local private key"] = "本地私钥",
	["Major mode"] = "主模式",
	["Maximum number of queued TCP output packets"] = "TCP 输出队列最大包数",
	["'net30', 'p2p', or 'subnet'"] = "net30、p2p 或 subnet",
	["Networking"] = "网络",
	["Number of allocated broadcast buffers"] = "分配的广播缓冲区数量",
	["Number of lines for log file history"] = "日志历史行数",
	["Only accept connections from given X509 name"] = "仅接受指定 X509 名称的连接",
	["Only process ping timeouts if routes exist"] = "仅在路由存在时处理 ping 超时",
	["Optimize TUN/TAP/UDP writes"] = "优化 TUN/TAP/UDP 写入",
	["Output to syslog and do not daemonize"] = "输出到 syslog 且不转为守护进程",
	["Pass environment variables to script"] = "向脚本传递环境变量",
	["Persist replay-protection state"] = "持久化重放保护状态",
	["Persist/unpersist ifconfig-pool"] = "持久化/取消持久化 ifconfig-pool",
	["Ping remote every n seconds over TCP/UDP port"] = "每 n 秒通过 TCP/UDP 端口 ping 远端",
	["PKCS#12 file containing keys"] = "包含密钥的 PKCS#12 文件",
	["Policy level over usage of external programs and scripts"] = "外部程序与脚本使用策略级别",
	["Proxy timeout in seconds"] = "代理超时时间（秒）",
	["Push an ifconfig option to remote"] = "向远端推送 ifconfig 选项",
	["Push options to peer"] = "向对端推送选项",
	["Query management channel for private key"] = "通过管理通道查询私钥",
	["Randomly choose remote server"] = "随机选择远端服务器",
	["Refuse connection if no custom client config"] = "无自定义客户端配置时拒绝连接",
	["Remap SIGUSR1 signals"] = "重映射 SIGUSR1 信号",
	["Remote host name or IP address"] = "远端主机名或 IP 地址",
	["Remote ping timeout"] = "远端 ping 超时",
	["Renegotiate data chan. key after bytes"] = "传输指定字节数后重新协商数据通道密钥",
	["Renegotiate data chan. key after packets"] = "传输指定包数后重新协商数据通道密钥",
	["Renegotiate data chan. key after seconds"] = "经过指定秒数后重新协商数据通道密钥",
	["Replay protection sliding window size"] = "重放保护滑动窗口大小",
	["Require explicit designation on certificate"] = "要求证书显式指定用途",
	["Require explicit key usage on certificate"] = "要求证书显式指定密钥用途",
	["Restart after remote ping timeout"] = "远端 ping 超时后重启",
	["Restrict the allowed ciphers to be negotiated"] = "限制可协商的加密算法",
	["Retransmit timeout on TLS control channel"] = "TLS 控制通道重传超时",
	["Retry indefinitely on HTTP proxy errors"] = "HTTP 代理错误时无限重试",
	["Retry indefinitely on Socks proxy errors"] = "Socks 代理错误时无限重试",
	["Route subnet to client"] = "将子网路由到客户端",
	["Run as an inetd or xinetd server"] = "作为 inetd 或 xinetd 服务运行",
	["Run script cmd on client connection"] = "客户端连接时运行脚本",
	["Run script cmd on client disconnection"] = "客户端断开时运行脚本",
	["Run up/down scripts for all restarts"] = "所有重启都运行 up/down 脚本",
	["Send notification to peer on disconnect"] = "断开时通知对端",
	["Service"] = "服务",
	["Set aside a pool of subnets"] = "预留一组子网地址池",
	["Set extended HTTP proxy options"] = "设置扩展 HTTP 代理选项",
	["Set GID to group"] = "设置进程 GID",
	["Set output verbosity"] = "设置输出详细级别",
	["Set size of real and virtual address hash tables"] = "设置真实与虚拟地址哈希表大小",
	["Set TCP/UDP MTU"] = "设置 TCP/UDP MTU",
	["Set the TCP/UDP receive buffer size"] = "设置 TCP/UDP 接收缓冲区大小",
	["Set the TCP/UDP send buffer size"] = "设置 TCP/UDP 发送缓冲区大小",
	["Set tun/tap adapter parameters"] = "设置 tun/tap 适配器参数",
	["Set tun/tap device MTU"] = "设置 tun/tap 设备 MTU",
	["Set tun/tap device overhead"] = "设置 tun/tap 设备额外开销",
	["Set tun/tap TX queue length"] = "设置 tun/tap 发送队列长度",
	["Set UID to user"] = "设置进程 UID",
	["Set upper bound on TCP MSS"] = "设置 TCP MSS 上限",
	["Shaping for peer bandwidth"] = "对端带宽整形",
	["Shell cmd to execute after tun device open"] = "打开 tun 设备后执行的 shell 命令",
	["Shell cmd to run after tun device close"] = "关闭 tun 设备后执行的 shell 命令",
	["Shell command to verify X509 name"] = "用于校验 X509 名称的 shell 命令",
	["Silence the output of replay warnings"] = "静默重放警告输出",
	["Size of cipher key"] = "密钥长度",
	["Specify a default gateway for routes"] = "为路由指定默认网关",
	["Specify whether the client is required to supply a valid certificate"] = "指定客户端是否必须提供有效证书",
	["Start OpenVPN in a hibernating state"] = "以休眠状态启动 OpenVPN",
	["Status file format version"] = "状态文件格式版本",
	["TCP/UDP port # for both local and remote"] = "本地与远端共用的 TCP/UDP 端口",
	["TCP/UDP port # for local (default=1194)"] = "本地 TCP/UDP 端口（默认 1194）",
	["TCP/UDP port # for remote (default=1194)"] = "远端 TCP/UDP 端口（默认 1194）",
	["Temporary directory for client-connect return file"] = "client-connect 返回文件的临时目录",
	["The highest supported TLS version"] = "支持的最高 TLS 版本",
	["The key direction for 'tls-auth' and 'secret' options"] = "tls-auth 与 secret 选项的密钥方向",
	["The lowest supported TLS version"] = "支持的最低 TLS 版本",
	["This completely disables cipher negotiation"] = "完全禁用加密算法协商",
	["Timeframe for key exchange"] = "密钥交换时间窗口",
	["TLS 1.3 or newer cipher"] = "TLS 1.3 及以上加密算法",
	["TLS cipher"] = "TLS 加密套件",
	["TOS passthrough (applies to IPv4 only)"] = "TOS 透传（仅 IPv4）",
	["tun/tap device"] = "tun/tap 设备",
	["tun/tap inactivity timeout"] = "tun/tap 空闲超时",
	["Type of used device"] = "设备类型",
	["Use fast LZO compression"] = "使用快速 LZO 压缩",
	["Use protocol"] = "使用协议",
	["Use tun/tap device node"] = "使用 tun/tap 设备节点",
	["Use username as common name"] = "使用用户名作为通用名",
	["VPN"] = "VPN",
	["Write log to file"] = "写日志到文件",
	["Write process ID to file"] = "写 PID 到文件",
	["Write status to file every n seconds"] = "每 n 秒写入一次状态文件"
}

local function translate(text)
	return zh[text] or _translate(text)
end

local value_labels = {
	[""] = "-- 更多选项 --",
	["-- remove --"] = "-- 移除此项 --",
	["yes"] = "是",
	["no"] = "否",
	["adaptive"] = "自适应",
	["udp"] = "UDP",
	["udp6"] = "UDP IPv6",
	["tcp-client"] = "TCP 客户端",
	["tcp-server"] = "TCP 服务端",
	["tcp6-client"] = "TCP IPv6 客户端",
	["tcp6-server"] = "TCP IPv6 服务端",
	["tun"] = "TUN 三层隧道",
	["tap"] = "TAP 二层桥接",
	["float"] = "允许漂移",
	["net30"] = "net30 点对点",
	["p2p"] = "点对点",
	["subnet"] = "子网",
	["system"] = "系统默认",
	["server"] = "服务端",
	["client"] = "客户端",
	["always"] = "始终",
	["maybe"] = "自动",
	["0"] = "0",
	["1"] = "1"
}

local function option_title(option)
	return option[4] or option[2]
end

local function option_desc(option)
	return "OpenVPN 指令: " .. tostring(option[2])
end

local function option_value_label(v)
	v = tostring(v)
	return value_labels[v] or v
end

local knownParams = {
	--
	--Widget
	--	ID
	--	Display name
	--	Default(s)
	--	Description
	--	Option(s)

	{ "service", translate("Service"), {
	-- initialisation and daemon options
		{ ListValue,
			"verb",
			{ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			translate("Set output verbosity") },
		{ Flag,
			"mlock",
			0,
			translate("Disable Paging") },
		{ Flag,
			"disable_occ",
			0,
			translate("Disable options consistency check") },
	--	{ Value,
	--		"user",
	--		"root",
	--		translate("Set UID to user") },
	--	{ Value,
	--		"group",
	--		"root",
	--		translate("Set GID to group") },
		{ Value,
			"cd",
			"/etc/openvpn",
			translate("Change to directory before initialization") },
		{ Value,
			"chroot",
			"/var/run",
			translate("Chroot to directory after initialization") },
	--	{ Value,
	--		"daemon",
	--		"Instance-Name",
	--		translate("Daemonize after initialization") },
	--	{ Value,
	--		"syslog",
	--		"Instance-Name",
	--		translate("Output to syslog and do not daemonize") },
		{ Flag,
			"passtos",
			0,
			translate("TOS passthrough (applies to IPv4 only)") },
	--	{ Value,
	--		"inetd",
	--		"nowait Instance-Name",
	--		translate("Run as an inetd or xinetd server") },
		{ Value,
			"log",
			"/var/log/openvpn.log",
			translate("Write log to file") },
		{ Value,
			"log_append",
			"/var/log/openvpn.log",
			translate("Append log to file") },
		{ Flag,
			"suppress_timestamps",
			0,
			translate("Don't log timestamps") },
	--	{ Value,
	--		"writepid",
	--		"/var/run/openvpn.pid",
	--		translate("Write process ID to file") },
		{ Value,
			"nice",
			0,
			translate("Change process priority") },
		{ Flag,
			"fast_io",
			0,
			translate("Optimize TUN/TAP/UDP writes") },
		{ Value,
			"echo",
			"some params echoed to log",
			translate("Echo parameters to log") },
		{ ListValue,
			"remap_usr1",
			{ "SIGHUP", "SIGTERM" },
			translate("Remap SIGUSR1 signals") },
		{ Value,
			"status",
			"/var/run/openvpn.status 5",
			translate("Write status to file every n seconds") },
		{ Value,
			"status_version",
			{ 1, 2 },
			translate("Status file format version") },	-- status
		{ Value,
			"mute",
			5,
			translate("Limit repeated log messages") },
		{ Value,
			"up",
			"/usr/bin/ovpn-up",
			translate("Shell cmd to execute after tun device open") },
		{ Value,
			"up_delay",
			5,
			translate("Delay tun/tap open and up script execution") },
		{ Value,
			"down",
			"/usr/bin/ovpn-down",
			translate("Shell cmd to run after tun device close") },
		{ Flag,
			"down_pre",
			0,
			translate("Call down cmd/script before TUN/TAP close") },
		{ Flag,
			"up_restart",
			0,
			translate("Run up/down scripts for all restarts") },
		{ Value,
			"route_up",
			"/usr/bin/ovpn-routeup",
			translate("Execute shell cmd after routes are added") },
		{ Value,
			"ipchange",
			"/usr/bin/ovpn-ipchange",
			translate("Execute shell command on remote IP change"),
			{ mode="p2p" } },
		{ DynamicList,
			"setenv",
			{ "VAR1 value1", "VAR2 value2" },
			translate("Pass environment variables to script") },
		{ Value,
			"tls_verify",
			"/usr/bin/ovpn-tlsverify",
			translate("Shell command to verify X509 name") },
		{ Value,
			"client_connect",
			"/usr/bin/ovpn-clientconnect",
			translate("Run script cmd on client connection") },
		{ Value,
			"client_disconnect",
			"/usr/bin/ovpn-clientdisconnect",
			translate("Run script cmd on client disconnection") },
		{ Value,
			"learn_address",
			"/usr/bin/ovpn-learnaddress",
			translate("Executed in server mode whenever an IPv4 address/route or MAC address is added to OpenVPN's internal routing table") },
		{ Value,
			"auth_user_pass_verify",
			"/usr/bin/ovpn-userpass via-env",
			translate("Executed in server mode on new client connections, when the client is still untrusted") },
		{ ListValue,
			"script_security",
			{ 0, 1, 2, 3 },
			translate("Policy level over usage of external programs and scripts") },
		{ ListValue,
			"compress",
			{ "lzo", "lz4" },
			translate("Enable a compression algorithm") },
	} },

	{ "networking", translate("Networking"), {
	-- socket config
		{ ListValue,
			"mode",
			{ "p2p", "server" },
			translate("Major mode") },
		{ Value,
			"local",
			"0.0.0.0",
			translate("Local host name or IP address") },
		{ Value,
			"port",
			1194,
			translate("TCP/UDP port # for both local and remote") },
		{ Value,
			"lport",
			1194,
			translate("TCP/UDP port # for local (default=1194)") },
		{ Value,
			"rport",
			1194,
			translate("TCP/UDP port # for remote (default=1194)") },
		{ Flag,
			"float",
			0,
			translate("Allow remote to change its IP or port") },
		{ Flag,
			"nobind",
			0,
			translate("Do not bind to local address and port") },
		{ Value,
			"dev",
			"tun0",
			translate("tun/tap device") },
		{ ListValue,
			"dev_type",
			{ "tun", "tap" },
			translate("Type of used device") },
		{ Value,
			"dev_node",
			"/dev/net/tun",
			translate("Use tun/tap device node") },
		{ Value,
			"ifconfig",
			"10.200.200.3 10.200.200.1",
			translate("Set tun/tap adapter parameters") },
		{ Flag,
			"ifconfig_noexec",
			0,
			translate("Don't actually execute ifconfig") },
		{ Flag,
			"ifconfig_nowarn",
			0,
			translate("Don't warn on ifconfig inconsistencies") },
		{ DynamicList,
			"route",
			"10.123.0.0 255.255.0.0",
			translate("Add route after establishing connection") },
		{ Value,
			"route_gateway",
			"10.234.1.1",
			translate("Specify a default gateway for routes") },
		{ Value,
			"route_delay",
			0,
			translate("Delay n seconds after connection") },
		{ Flag,
			"route_noexec",
			0,
			translate("Don't add routes automatically") },
		{ Flag,
			"route_nopull",
			0,
			translate("Don't pull routes automatically") },
		{ Flag,
			"allow_recursive_routing",
			0,
			translate("Don't drop incoming tun packets with same destination as host") },
		{ ListValue,
			"mtu_disc",
			{ "yes", "maybe", "no" },
			translate("Enable Path MTU discovery") },
		{ Flag,
			"mtu_test",
			0,
			translate("Empirically measure MTU") },
		{ ListValue,
			"comp_lzo",
			{ "yes", "no", "adaptive" },
			translate("Use fast LZO compression") },
		{ Flag,
			"comp_noadapt",
			0,
			translate("Don't use adaptive lzo compression"),
			{ comp_lzo=1 } },
		{ Value,
			"link_mtu",
			1500,
			translate("Set TCP/UDP MTU") },
		{ Value,
			"tun_mtu",
			1500,
			translate("Set tun/tap device MTU") },
		{ Value,
			"tun_mtu_extra",
			1500,
			translate("Set tun/tap device overhead") },
		{ Value,
			"fragment",
			1500,
			translate("Enable internal datagram fragmentation"),
			{ proto="udp" } },
		{ Value,
			"mssfix",
			1500,
			translate("Set upper bound on TCP MSS"),
			{ proto="udp" } },
		{ Value,
			"sndbuf",
			65536,
			translate("Set the TCP/UDP send buffer size") },
		{ Value,
			"rcvbuf",
			65536,
			translate("Set the TCP/UDP receive buffer size") },
		{ Value,
			"txqueuelen",
			100,
			translate("Set tun/tap TX queue length") },
		{ Value,
			"shaper",
			10240,
			translate("Shaping for peer bandwidth") },
		{ Value,
			"inactive",
			240,
			translate("tun/tap inactivity timeout") },
		{ Value,
			"keepalive",
			"10 60",
			translate("Helper directive to simplify the expression of --ping and --ping-restart in server mode configurations") },
		{ Value,
			"ping",
			30,
			translate("Ping remote every n seconds over TCP/UDP port") },
		{ Value,
			"ping_exit",
			120,
			translate("Remote ping timeout") },
		{ Value,
			"ping_restart",
			60,
			translate("Restart after remote ping timeout") },
		{ Flag,
			"ping_timer_rem",
			0,
			translate("Only process ping timeouts if routes exist") },
		{ Flag,
			"persist_tun",
			0,
			translate("Keep tun/tap device open on restart") },
		{ Flag,
			"persist_key",
			0,
			translate("Don't re-read key on restart") },
		{ Flag,
			"persist_local_ip",
			0,
			translate("Keep local IP address on restart") },
		{ Flag,
			"persist_remote_ip",
			0,
			translate("Keep remote IP address on restart") },
	-- management channel
		{ Value,
			"management",
			"127.0.0.1 31194 /etc/openvpn/mngmt-pwds",
			translate("Enable management interface on <em>IP</em> <em>port</em>") },
	-- management
		{ Flag,
			"management_query_passwords",
			0,
			translate("Query management channel for private key") },
	-- management
		{ Flag,
			"management_hold",
			0,
			translate("Start OpenVPN in a hibernating state") },
	-- management
		{ Value,
			"management_log_cache",
			100,
			translate("Number of lines for log file history") },
		{ ListValue,
			"topology",
			{ "net30", "p2p", "subnet" },
			translate("'net30', 'p2p', or 'subnet'"),
			{dev_type="tun" } },
	} },

	{ "vpn", translate("VPN"), {
		{ Value,
			"server",
			"10.200.200.0 255.255.255.0",
			translate("Configure server mode"),
			{ client="0" }, { client="" } },
		{ Value,
			"server_bridge",
			"10.200.200.1 255.255.255.0 10.200.200.200 10.200.200.250",
			translate("Configure server bridge"),
			{ client="0" }, { client="" } },
		{ DynamicList,
			"push",
			{ "redirect-gateway", "comp-lzo" },
			translate("Push options to peer"),
			{ client="0" }, { client="" } },
		{ Flag,
			"push_reset",
			0,
			translate("Don't inherit global push options"),
			{ client="0" }, { client="" } },
		{ Flag,
			"disable",
			0,
			translate("Client is disabled"),
			{ client="0" }, { client="" } },
		{ Value,
			"ifconfig_pool",
			"10.200.200.100 10.200.200.150 255.255.255.0",
			translate("Set aside a pool of subnets"),
			{ client="0" }, { client="" } },
		{ Value,
			"ifconfig_pool_persist",
			"/etc/openvpn/ipp.txt 600",
			translate("Persist/unpersist ifconfig-pool"),
			{ client="0" }, { client="" } },
		{ Value,
			"ifconfig_push",
			"10.200.200.1 255.255.255.255",
			translate("Push an ifconfig option to remote"),
			{ client="0" }, { client="" } },
		{ Value,
			"iroute",
			"10.200.200.0 255.255.255.0",
			translate("Route subnet to client"),
			{ client="0" }, { client="" } },
		{ Flag,
			"client_to_client",
			0,
			translate("Allow client-to-client traffic"),
			{ client="0" }, { client="" } },
		{ Flag,
			"duplicate_cn",
			0,
			translate("Allow multiple clients with same certificate"),
			{ client="0" }, { client="" } },
		{ Value,
			"client_config_dir",
			"/etc/openvpn/ccd",
			translate("Directory for custom client config files"),
			{ client="0" }, { client="" } },
		{ Flag,
			"ccd_exclusive",
			0,
			translate("Refuse connection if no custom client config"),
			{ client="0" }, { client="" } },
		{ Value,
			"tmp_dir",
			"/var/run/openvpn",
			translate("Temporary directory for client-connect return file"),
			{ client="0" }, { client="" } },
		{ Value,
			"hash_size",
			"256 256",
			translate("Set size of real and virtual address hash tables"),
			{ client="0" }, { client="" } },
		{ Value,
			"bcast_buffers",
			256,
			translate("Number of allocated broadcast buffers"),
			{ client="0" }, { client="" } },
		{ Value,
			"tcp_queue_limit",
			64,
			translate("Maximum number of queued TCP output packets"),
			{ client="0" }, { client="" } },
		{ Value,
			"max_clients",
			10,
			translate("Allowed maximum of connected clients"),
			{ client="0" }, { client="" } },
		{ Value,
			"max_routes_per_client",
			256,
			translate("Allowed maximum of internal"),
			{ client="0" }, { client="" } },
		{ Value,
			"connect_freq",
			"3 10",
			translate("Allowed maximum of new connections"),
			{ client="0" }, { client="" } },
		{ Flag,
			"username_as_common_name",
			0,
			translate("Use username as common name"),
			{ client="0" }, { client="" } },
		{ Flag,
			"client",
			0,
			translate("Configure client mode") },
		{ Flag,
			"pull",
			0,
			translate("Accept options pushed from server"),
			{ client="1" } },
		{ FileUpload,
			"auth_user_pass",
			"/etc/openvpn/userpass.txt",
			translate("Authenticate using username/password"),
			{ client="1" } },
		{ ListValue,
			"auth_retry",
			{ "none", "nointeract", "interact" },
			translate("Handling of authentication failures"),
			{ client="1" } },
		{ Value,
			"explicit_exit_notify",
			1,
			translate("Send notification to peer on disconnect"),
			{ client="1" } },
		{ DynamicList,
			"remote",
			"1.2.3.4",
			translate("Remote host name or IP address") },
		{ Flag,
			"remote_random",
			0,
			translate("Randomly choose remote server"),
			{ client="1" } },
		{ ListValue,
			"proto",
			{ "udp", "tcp-client", "tcp-server" },
			translate("Use protocol"),
			{ client="1" } },
		{ Value,
			"connect_retry",
			5,
			translate("Connection retry interval"),
			{ proto="tcp-client" }, { client="1" } },
		{ Value,
			"http_proxy",
			"192.168.1.100 8080",
			translate("Connect to remote host through an HTTP proxy"),
			{ client="1" } },
		{ Flag,
			"http_proxy_retry",
			0,
			translate("Retry indefinitely on HTTP proxy errors"),
			{ client="1" } },
		{ Value,
			"http_proxy_timeout",
			5,
			translate("Proxy timeout in seconds"),
			{ client="1" } },
		{ DynamicList,
			"http_proxy_option",
			{ "VERSION 1.0", "AGENT OpenVPN/2.0.9" },
			translate("Set extended HTTP proxy options"),
			{ client="1" } },
		{ Value,
			"socks_proxy",
			"192.168.1.200 1080",
			translate("Connect through Socks5 proxy"),
			{ client="1" } },
	-- client && socks_proxy
		{ Value,
			"socks_proxy_retry",
			5,
			translate("Retry indefinitely on Socks proxy errors"),
			{ client="1" } },
		{ Value,
			"resolv_retry",
			"infinite",
			translate("If hostname resolve fails, retry"),
			{ client="1" } },
		{ ListValue,
			"redirect_gateway",
			{ "", "local", "def1", "local def1" },
			translate("Automatically redirect default route"),
			{ client="1" } },
		{ Value,
			"verify_client_cert",
			{  "none", "optional", "require" },
			translate("Specify whether the client is required to supply a valid certificate") },
	} },

	{ "cryptography", translate("Cryptography"), {
		{ FileUpload,
			"secret",
			"/etc/openvpn/secret.key",
			translate("Enable Static Key encryption mode (non-TLS)") },
	-- parse
		{ Value,
			"auth",
			"SHA1",
			translate("HMAC authentication for packets") },
	-- parse
		{ Value,
			"cipher",
			{
				"AES-128-CBC",
				"AES-128-CFB",
				"AES-128-CFB1",
				"AES-128-CFB8",
				"AES-128-GCM",
				"AES-128-OFB",
				"AES-192-CBC",
				"AES-192-CFB",
				"AES-192-CFB1",
				"AES-192-CFB8",
				"AES-192-GCM",
				"AES-192-OFB",
				"AES-256-CBC",
				"AES-256-CFB",
				"AES-256-CFB1",
				"AES-256-CFB8",
				"AES-256-GCM",
				"AES-256-OFB",
				"BF-CBC",
				"BF-CFB",
				"BF-OFB",
				"CAST5-CBC",
				"CAST5-CFB",
				"CAST5-OFB",
				"DES-CBC",
				"DES-CFB",
				"DES-CFB1",
				"DES-CFB8",
				"DES-EDE-CBC",
				"DES-EDE-CFB",
				"DES-EDE-OFB",
				"DES-EDE3-CBC",
				"DES-EDE3-CFB",
				"DES-EDE3-CFB1",
				"DES-EDE3-CFB8",
				"DES-EDE3-OFB",
				"DES-OFB",
				"DESX-CBC",
				"RC2-40-CBC",
				"RC2-64-CBC",
				"RC2-CBC",
				"RC2-CFB",
				"RC2-OFB"
			},
			translate("Encryption cipher for packets") },
	-- parse
		{ Value,
			"keysize",
			1024,
			translate("Size of cipher key") },
	-- parse
		{ Value,
			"engine",
			"dynamic",
			translate("Enable OpenSSL hardware crypto engines") },
		{ Value,
			"replay_window",
			"64 15",
			translate("Replay protection sliding window size") },
		{ Flag,
			"mute_replay_warnings",
			0,
			translate("Silence the output of replay warnings") },
		{ Value,
			"replay_persist",
			"/var/run/openvpn-replay-state",
			translate("Persist replay-protection state") },
		{ Flag,
			"tls_server",
			0,
			translate("Enable TLS and assume server role"),
			{ tls_client="" }, { tls_client="0" } },
		{ Flag,
			"tls_client",
			0,
			translate("Enable TLS and assume client role"),
			{ tls_server="" }, { tls_server="0" } },
		{ FileUpload,
			"ca",
			"/etc/easy-rsa/keys/ca.crt",
			translate("Certificate authority") },
		{ FileUpload,
			"dh",
			"/etc/easy-rsa/keys/dh1024.pem",
			translate("Diffie-Hellman parameters") },
		{ FileUpload,
			"cert",
			"/etc/easy-rsa/keys/some-client.crt",
			translate("Local certificate") },
		{ FileUpload,
			"key",
			"/etc/easy-rsa/keys/some-client.key",
			translate("Local private key") },
		{ FileUpload,
			"pkcs12",
			"/etc/easy-rsa/keys/some-client.pk12",
			translate("PKCS#12 file containing keys") },
		{ ListValue,
			"key_method",
			{ 1, 2 },
			translate("Enable TLS and assume client role") },
		{ DynamicList,
			"tls_cipher",
			{
				"TLS-ECDHE-ECDSA-WITH-AES-256-GCM-SHA384",
				"TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384",
				"TLS-DHE-RSA-WITH-AES-256-GCM-SHA384",
				"TLS-ECDHE-ECDSA-WITH-CHACHA20-POLY1305-SHA256",
				"TLS-ECDHE-RSA-WITH-CHACHA20-POLY1305-SHA256",
				"TLS-DHE-RSA-WITH-CHACHA20-POLY1305-SHA256",
				"TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256",
				"TLS-ECDHE-RSA-WITH-AES-128-GCM-SHA256",
				"TLS-DHE-RSA-WITH-AES-128-GCM-SHA256",
				"TLS-ECDHE-ECDSA-WITH-AES-256-CBC-SHA384",
				"TLS-ECDHE-RSA-WITH-AES-256-CBC-SHA384",
				"TLS-DHE-RSA-WITH-AES-256-CBC-SHA256",
				"TLS-ECDHE-ECDSA-WITH-AES-128-CBC-SHA256",
				"TLS-ECDHE-RSA-WITH-AES-128-CBC-SHA256",
				"TLS-DHE-RSA-WITH-AES-128-CBC-SHA256",
				"TLS-ECDHE-ECDSA-WITH-AES-256-CBC-SHA",
				"TLS-ECDHE-RSA-WITH-AES-256-CBC-SHA",
				"TLS-DHE-RSA-WITH-AES-256-CBC-SHA",
				"TLS-ECDHE-ECDSA-WITH-AES-128-CBC-SHA",
				"TLS-ECDHE-RSA-WITH-AES-128-CBC-SHA",
				"TLS-DHE-RSA-WITH-AES-128-CBC-SHA"
			},
			translate("TLS cipher") },
		{ DynamicList,
			"tls_ciphersuites",
			{
				"TLS_AES_256_GCM_SHA384",
				"TLS_AES_128_GCM_SHA256",
				"TLS_CHACHA20_POLY1305_SHA256"
			},
			translate("TLS 1.3 or newer cipher") },
		{ Value,
			"tls_timeout",
			2,
			translate("Retransmit timeout on TLS control channel") },
		{ Value,
			"reneg_bytes",
			1024,
			translate("Renegotiate data chan. key after bytes") },
		{ Value,
			"reneg_pkts",
			100,
			translate("Renegotiate data chan. key after packets") },
		{ Value,
			"reneg_sec",
			3600,
			translate("Renegotiate data chan. key after seconds") },
		{ Value,
			"hand_window",
			60,
			translate("Timeframe for key exchange") },
		{ Value,
			"tran_window",
			3600,
			translate("Key transition window") },
		{ Flag,
			"single_session",
			0,
			translate("Allow only one session") },
		{ Flag,
			"tls_exit",
			0,
			translate("Exit on TLS negotiation failure") },
		{ Value,
			"tls_auth",
			"/etc/openvpn/tlsauth.key",
			translate("Additional authentication over TLS") },
		{ Value,
			"tls_crypt",
			"/etc/openvpn/tlscrypt.key",
			translate("Encrypt and authenticate all control channel packets with the key") },
	--	{ Value,
	--		"askpass",
	--		"[file]",
	--		translate("Get PEM password from controlling tty before we daemonize") },
		{ Flag,
			"auth_nocache",
			0,
			translate("Don't cache --askpass or --auth-user-pass passwords") },
		{ Value,
			"tls_remote",
			"remote_x509_name",
			translate("Only accept connections from given X509 name") },
		{ ListValue,
			"ns_cert_type",
			{ "client", "server" },
			translate("Require explicit designation on certificate") },
		{ ListValue,
			"remote_cert_tls",
			{ "client", "server" },
			translate("Require explicit key usage on certificate") },
		{ Value,
			"crl_verify",
			"/etc/easy-rsa/keys/crl.pem",
			translate("Check peer certificate against a CRL") },
		{ Value,
			"tls_version_min",
			"1.0",
			translate("The lowest supported TLS version") },
		{ Value,
			"tls_version_max",
			"1.2",
			translate("The highest supported TLS version") },
		{ ListValue,
			"key_direction",
			{ 0, 1 },
			translate("The key direction for 'tls-auth' and 'secret' options") },
		{ Flag,
			"ncp_disable",
			0,
			translate("This completely disables cipher negotiation") },
		{ Value,
			"ncp_ciphers",
			"AES-256-GCM:AES-128-GCM",
			translate("Restrict the allowed ciphers to be negotiated") },
	} }
}


local cts = { }
local params = { }
local title = ""

local m = Map("openvpn")
m.redirect = luci.dispatcher.build_url("admin", "services", "openvpn")
m.apply_on_parse = true

local p = m:section( SimpleSection )
p.template = "openvpn/pageswitch"
p.mode     = "advanced"
p.instance = arg[1]
p.category = arg[2] or knownParams[1][1]

for _, c in ipairs(knownParams) do
	cts[#cts+1] = { id = c[1], title = c[2] }
	if c[1] == p.category then
		title = c[2]
		params = c[3]
	end
end

p.categories = cts


local s = m:section(
	NamedSection, arg[1], "openvpn", title
)
s.template = "openvpn/nsection"

s.addremove = false
s.anonymous = true


for _, option in ipairs(params) do
	local o = s:option(
		option[1], option[2],
		option_title(option), option_desc(option)
	)
	o.title = option_title(option)
	o.description = option_desc(option)

	o.optional = true

	if option[1] == DummyValue then
		o.value = option[3]
	elseif option[1] == FileUpload then

		o.initial_directory = "/etc/openvpn"

		function o.cfgvalue(self, section)
			local cfg_val = AbstractValue.cfgvalue(self, section)

			if cfg_val then
				return cfg_val
			end
		end

		function o.formvalue(self, section)
			local sel_val = AbstractValue.formvalue(self, section)
			local txt_val = luci.http.formvalue("cbid."..self.map.config.."."..section.."."..self.option..".textbox")

			if sel_val and sel_val ~= "" then
				return sel_val
			end

			if txt_val and txt_val ~= "" then
				return txt_val
			end
		end

		function o.remove(self, section)
			local cfg_val = AbstractValue.cfgvalue(self, section)
			local txt_val = luci.http.formvalue("cbid."..self.map.config.."."..section.."."..self.option..".textbox")

			if cfg_val and fs.access(cfg_val) and txt_val == "" then
				fs.unlink(cfg_val)
			end
			return AbstractValue.remove(self, section)
		end
	elseif option[1] == Flag then
		o.default = nil
	else
		if option[1] == DynamicList then
			function o.cfgvalue(...)
				local val = AbstractValue.cfgvalue(...)
				return ( val and type(val) ~= "table" ) and { val } or val
			end
		end

		if type(option[3]) == "table" then
			if o.optional then o:value("", option_value_label("-- remove --")) end
			for _, v in ipairs(option[3]) do
				v = tostring(v)
				o:value(v, option_value_label(v))
			end
			o.default = tostring(option[3][1])
		else
			o.default = tostring(option[3])
		end
	end

	for i=5,#option do
		if type(option[i]) == "table" then
			o:depends(option[i])
		end
	end
end

return m
