#!/bin/sh /etc/rc.common

START=14
STOP=92

USE_PROCD=1

loop_atsd() {
	local rule=$1
	local target=false
	config_get _nettype $rule nettype ""
	config_get _proto $rule proto ""
	config_get _share_channel $rule share_channel ""

	if [ -n "$_nettype" ];then
		target=true
	else
		if [ "$_proto" == "wwan" -o "$_proto" == "netmanager" ];then
			target=true
		fi
	fi
	if [ $target == true ];then
		if [ -z "$_share_channel" -o "$_share_channel" == "$rule" ];then
			procd_open_instance
			procd_set_param command /usr/sbin/atsd -i "$rule"
			procd_set_param respawn 5 5 -1
			procd_close_instance
		fi
	fi
}

start_service() {
	config_load network
	config_foreach loop_atsd interface
}
