#!/bin/sh /etc/rc.common

START=90
STOP=92
USE_PROCD=1

checker_interface() {
	local rule=$1
	config_get proto "$rule" proto
	config_get disabled "$rule" disabled
	config_get mode "$rule" mode

	if [ "$mode" == "odu" -a "$disabled" != "1" ];then
		if [ "$proto" == "wwan" ];then
			procd_open_instance
			procd_set_param command /usr/sbin/atserver-sniffer -i "$rule"
			procd_set_param respawn 5 5 -1
			procd_close_instance
		fi
	fi
}
start_service() {
	config_load "network"
	config_foreach checker_interface interface
}
