#!/bin/sh /etc/rc.common

START=99
STOP=92

USE_PROCD=1

start_service() {
	local enable=$(uci -q get cellular_record.basic.enabled)

	[ "$enable" != 1 ] && return
	procd_open_instance
	procd_set_param command /usr/sbin/cellular_record
	procd_set_param respawn 5 5 -1
	procd_close_instance
}
