#!/bin/sh /etc/rc.common

START=29
STOP=71

USE_PROCD=1



start_service() {
	local cellular_cpe=$(uci -q get cloudd.config.cellular_cpe)
	local cellular_sn=$(uci -q get cloudd.config.cellular_sn)
	[ -z "$cellular_cpe" ] && cellular_cpe="cpe"
	local cellular_disabled=$(uci -q get network."$cellular_cpe".disabled)
	local cellular_mode=$(uci -q get network.$cellular_cpe.mode)

	parameter=""
	if [ -f /usr/bin/bdinfo ]; then
		mac_addr=$(uci get oem.board.id|sed 's/://g'|grep -ioE [a-f0-9]{12})
		ptype=$(uci -q get oem.board.ptype)
	else
		mac_addr=$(cat /online/vendor/macaddr)
		ptype="rt"
	fi

	[ "$ptype" = "ac" ] && max_child=20 || max_child=10
	if uci -q get mosquitto.bridge_ac; then
		max_child=20
	fi

	if [ "$cellular_sn" == "1" -a "$cellular_disabled" != "1" -a "$cellular_mode" == "odu" ];then
		sn=$(uci -q get cellular_init.$cellular_cpe.sn)
	fi

	if [ -n "$sn" ];then
		parameter="-m ${sn} -M ${mac_addr:-006688000000}"
	else
		parameter="-m ${mac_addr:-006688000000}"
	fi

	procd_open_instance
	procd_set_param command /usr/bin/cloudd $parameter -c "$max_child"
	procd_set_param respawn
	procd_set_param limits core="unlimited"
	procd_close_instance
	cloudd_cron
}
