#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1

_name="conn_detect"
_exec="/usr/sbin/${_name}"

start_service() {
    interval=$(uci -q get $_name.config.interval)

	procd_open_instance
	procd_set_param command $_exec -i $interval
	procd_set_param respawn
	procd_set_param limits core="unlimited"
	procd_close_instance
}
