#!/bin/sh /etc/rc.common

START=15
STOP=10

USE_PROCD=1

_name="cpesel"
_exec="/usr/bin/${_name}.sh"

loop_sim() {
	local rule=$1
	local _cur=
	local _max=
	local _mode=
	local _gval=
	local _index=

	config_get _cur $rule cur
	config_get _max $rule max
	config_get _mode $rule mode
	config_get _gval $rule gval
	gIndex=${rule##*[A-Za-z]}

	cellular=$(uci -q get network.globals.default_cellular)
	[ -z "$cellular" ] && cellular="cpe"
	cellularIndex=${cellular##*[A-Za-z]}
	if [ "$cellularIndex" == "0" -a -n "$gIndex" ];then
		cellular_rule="${cellular%%[0-9]*}$gIndex"
	else
		cellular_rule="${cellular}$gIndex"
	fi

	local cellular_disabled=$(uci -q get network.$cellular_rule.disabled)
	local odu_model=$(uci -q get network.$cellular_rule.odu_model)
	if [ "$cellular_disabled" == "1" -o "$odu_model" == "NRFAMILY" ];then
		return 0
	fi

	scansim=$(uci -q get cellular_init.$cellular_rule.scansim)
	[ "$scansim" == "1"  ] && return 0

	rm -f /var/run/rpcd/cpesel$gIndex.json.lock

	procd_open_instance
	procd_set_param command "$_exec" -m "$_max" -c "${_cur:-1}" -M "$_mode" -b $1
	procd_set_param respawn
	procd_set_param limits core="unlimited"
	procd_close_instance
}

start_service(){
	config_load cpesel
	config_foreach loop_sim cpesel
}
