#!/bin/sh /etc/rc.common

START=97
STOP=10

USE_PROCD=1

_exec="/usr/bin/fanctrl.sh"

start_service() {
	procd_open_instance
	procd_set_param command "$_exec" 
	procd_set_param respawn
	procd_close_instance
}
