#!/bin/sh /etc/rc.common

START=13
STOP=92

USE_PROCD=1

start_service() {
	sleep 1
	procd_open_instance
	procd_set_param command /usr/sbin/infocd
	procd_set_param respawn 5 5 -1
	procd_close_instance
	procd_open_instance
	procd_set_param command /usr/sbin/infocd_consumer
	procd_set_param respawn 5 5 -1
	procd_close_instance
}
