#!/bin/sh /etc/rc.common

START=02
STOP=98

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/kpshd
	procd_set_param respawn
	procd_set_param limits core="unlimited"
	procd_close_instance
}
