#!/bin/sh /etc/rc.common

START=99
STOP=92

USE_PROCD=1

loop_sim() {
	local rule=$1
	local rulekey=""
	config_get _cur $rule cur
	gIndex=${rule##*[A-Za-z]}
	[ -z "$_cur" ] && _cur="1"

	local sim="sim"
	cellular=$(uci -q get network.globals.default_cellular)
	[ -z "$cellular" ] && cellular="cpe"
	cellularIndex=${cellular##*[A-Za-z]}
	if [ "$cellularIndex" == "0" -a -n "$gIndex" ];then
		rulekey="${cellular%%[0-9]*}$gIndex"
	else
		rulekey="${cellular}$gIndex"
		sim="sim$gIndex"
	fi
	local stype=$(uci -q get cpesel.${sim}.stype)
	if echo "$stype"|grep -q '0';then
		procd_open_instance
		procd_set_param command /usr/sbin/smsd -i $rulekey
		procd_set_param respawn 5 5 -1
		procd_close_instance
	fi
}
start_service() {
	sleep 2
	config_load cpesel
	config_foreach loop_sim cpesel
}
