#!/bin/sh
. /lib/functions/oem.sh

board_def="$(get_def_board)"
gMac="$(uci get oem.board.id|tr -d :)"
[ -f "/oem/$board_def/config/99_cpe_dynamic" ] && . /oem/$board_def/config/99_cpe_dynamic
_cpe_dynamic="${_cpe_dynamic:-0}"
_default_bridge="bridge"
_default_remoteid="$gMac"

if [ "X$1" != "Xfixup" ]; then
	uci batch <<-EOF
		set mosquitto.owrt=owrt
		set mosquitto.owrt.use_uci=1
		set mosquitto.mosquitto=mosquitto
		set mosquitto.mosquitto.log_dest=syslog
		set mosquitto.mosquitto.log_types=warning
		set mosquitto.mosquitto.allow_anonymous='1'
		set mosquitto.listener=listener
		set mosquitto.listener.port=1883
		set mosquitto.listener.no_remote_access="0"
	EOF
fi

if [ $_cpe_dynamic -eq -1 ];then
	_default_bridge="bridge_ac"
	_default_remoteid="${gMac}ap"
uci batch <<-EOF
	delete mosquitto.bridge
	set mosquitto.bridge=bridge
	set mosquitto.bridge.connection="$gMac"
	set mosquitto.bridge.remote_clientid="$gMac"
	set mosquitto.bridge.remote_username=router
	set mosquitto.bridge.address="$gMac.dev.nradio.com.cn"
	set mosquitto.bridge.keepalive_interval="10"
	set mosquitto.bridge.notifications=1
	set mosquitto.bridge.notifications_local_only=1
	set mosquitto.bridge.restart_timeout=5
	set mosquitto.bridge.try_private=0

	delete mosquitto.bridge.topic
	add_list mosquitto.bridge.topic="sysinfo/# out 1 \"\" $gMac/"
	add_list mosquitto.bridge.topic="exec/# both 1 rpc/ $gMac/"
	add_list mosquitto.bridge.topic="kp/mosca/$gMac/# out 1 \"\" \"\""
	add_list mosquitto.bridge.topic='kp/$gMac/+/# in 1 "" ""'
	add_list mosquitto.bridge.topic='mosca/# in 1 kp/$gMac/ kp/FFFFFFFFFFFF/'
EOF
fi

if [ "X$1" != "Xfixup" ]; then
	uci batch <<-EOF
		delete mosquitto.$_default_bridge
		set mosquitto.$_default_bridge=bridge
		set mosquitto.$_default_bridge.connection="${_default_remoteid}"
		set mosquitto.$_default_bridge.remote_clientid="${_default_remoteid}"
		set mosquitto.$_default_bridge.remote_username=router
		set mosquitto.$_default_bridge.address=mboard
		set mosquitto.$_default_bridge.notifications=1
		set mosquitto.$_default_bridge.restart_timeout=5
		set mosquitto.$_default_bridge.keepalive_interval="10"
		set mosquitto.$_default_bridge.try_private=1
	EOF
fi

uci batch <<-EOF
	delete mosquitto.$_default_bridge.topic
	add_list mosquitto.$_default_bridge.topic="kp/# out 1 local/ ${_default_remoteid}/"
	add_list mosquitto.$_default_bridge.topic='kp/# both 1 "" ""'
	add_list mosquitto.$_default_bridge.topic='+/# in 1 kp/${_default_remoteid}/ kp/FFFFFFFFFFFF/'
EOF
