#!/bin/ash

uci set network.wan=interface
uci set network.wan.proto='dhcp'
uci set network.wan.defaultroute='0'
uci set network.wan.disabled='1'
uci set network.wan.device='eth0'

uci set network.wan6=interface
uci set network.wan6.proto='dhcpv6'
uci set network.wan6.ipv6='0'
uci set network.wan6.defaultroute='0'
uci set network.wan6.disabled='1'
uci set network.wan6.device='eth0'
